apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/ankesh/bin/kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: /home/ankesh/bin/kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://postgres:password@db::5432/postgres
          image: backend
          name: backend
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
