apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: front-vol
  name: front-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
